//! Context utilities for error handling
//!
//! This module provides utilities for adding contextual information to errors.

#[cfg(feature = "std")]
extern crate std;

#[cfg(all(not(feature = "std"), feature = "alloc"))]
extern crate alloc;

// Use alloc for formatting if std is not enabled
#[cfg(all(not(feature = "std"), feature = "alloc"))]
use alloc::format;

// Use std for formatting if std is enabled
#[cfg(feature = "std")]
use std::format;

#[cfg(feature = "alloc")]
use super::errors::{Error, ErrorCategory, ErrorSource};
#[cfg(feature = "alloc")]
use core::fmt::Display;

/// Provides the `context` method for `Result`.
///
/// This trait is only available when the `alloc` feature is enabled.
#[cfg(feature = "alloc")]
pub trait ResultExt<T, E> {
    /// Wraps the error value with additional context.
    fn context<C>(self, context: C) -> core::result::Result<T, Error>
    where
        C: Display + core::fmt::Debug + Send + Sync + 'static;

    /// Wraps the error value with context generated by a closure.
    fn with_context<C, F>(self, f: F) -> core::result::Result<T, Error>
    where
        C: Display + core::fmt::Debug + Send + Sync + 'static,
        F: FnOnce() -> C;
}

#[cfg(feature = "alloc")]
impl<T, E> ResultExt<T, E> for core::result::Result<T, E>
where
    E: ErrorSource + Send + Sync + 'static,
{
    fn context<C>(self, context: C) -> core::result::Result<T, Error>
    where
        C: Display + core::fmt::Debug + Send + Sync + 'static,
    {
        match self {
            Ok(value) => Ok(value),
            Err(error) => Err(Error::new(
                ErrorCategory::System,
                0,
                format!("{}: {}", context, error.message()),
            )),
        }
    }

    fn with_context<C, F>(self, f: F) -> core::result::Result<T, Error>
    where
        C: Display + core::fmt::Debug + Send + Sync + 'static,
        F: FnOnce() -> C,
    {
        match self {
            Ok(value) => Ok(value),
            Err(error) => Err(Error::new(
                ErrorCategory::System,
                0,
                format!("{}: {}", f(), error.message()),
            )),
        }
    }
}

#[cfg(all(feature = "std", feature = "alloc"))]
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        // In std context, we could potentially convert the ErrorSource trait object to std::error::Error
        // But we would need to ensure ErrorSource extends std::error::Error for this to work
        match &self.source {
            Some(_src) => {
                // This is a bit of a hack since we can't directly downcast the trait object
                // without knowing the concrete type, and we don't have a direct way to convert
                // a dyn ErrorSource to a dyn std::error::Error
                None
            }
            None => None,
        }
    }
}
